//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_final.Modelo_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arista
    {
        public int Id { get; set; }
        public string Demora { get; set; }
        public double Precio { get; set; }
        public Nullable<int> Destino_Id { get; set; }
        public Nullable<int> Origen_Id { get; set; }
        public Nullable<int> Viaje_Id { get; set; }
    
        public virtual Destino Destino { get; set; }
        public virtual Destino Destino1 { get; set; }
        public virtual Viaje Viaje { get; set; }
    }
}
