//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_final.Modelo_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseModelo_EF : DbContext
    {
        public BaseModelo_EF()
            : base("name=BaseModelo_EF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<Destino> Destino { get; set; }
        public virtual DbSet<Horario> Horario { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<Fila> Filas { get; set; }
        public virtual DbSet<Celda> Celdas { get; set; }
        public virtual DbSet<Distribucion> Distribucions { get; set; }
        public virtual DbSet<Viaje> Viajes { get; set; }
        public virtual DbSet<Arista> Aristas { get; set; }
        public virtual DbSet<Boleto> Boletoes { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
    }
}
