//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_final.Modelo_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleto
    {
        public int ID { get; set; }
        public int Asiento { get; set; }
        public string FechaEmision { get; set; }
        public string Fecha { get; set; }
        public string Precio { get; set; }
        public string HoraSalida { get; set; }
        public string HoraSalidaAdicional { get; set; }
        public string HoraLlegada { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Destino_Id { get; set; }
        public Nullable<int> Origen_Id { get; set; }
        public Nullable<int> Pago_Id { get; set; }
        public Nullable<int> Pasajero_ID { get; set; }
        public Nullable<int> Recorrido_Id { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Destino Destino { get; set; }
        public virtual Destino Destino1 { get; set; }
        public virtual Pago Pago { get; set; }
        public virtual Viaje Viaje { get; set; }
    }
}
