//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_final.Modelo_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Celda
    {
        public int Id { get; set; }
        public int Value { get; set; }
        public System.DateTime Fecha_registro { get; set; }
        public Nullable<int> Fila_Id { get; set; }
    
        public virtual Fila Fila { get; set; }
    }
}
