//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_final.Modelo_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int Id { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public string Correo { get; set; }
        public string Fechanac { get; set; }
        public string Fechareg { get; set; }
        public string Sexo { get; set; }
        public string Tipo { get; set; }
    }
}
