//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_final.Modelo_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public int Id { get; set; }
        public string Hora { get; set; }
        public Nullable<int> Distribucion_Id { get; set; }
        public Nullable<int> Viaje_Id { get; set; }
        public Nullable<int> Frecuencia_Id { get; set; }
    
        public virtual Distribucion Distribucion { get; set; }
        public virtual Fila Fila { get; set; }
        public virtual Viaje Viaje { get; set; }
    }
}
