//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_final.Modelo_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pago()
        {
            this.Boletoes = new HashSet<Boleto>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public int Boleto { get; set; }
        public string Tipo { get; set; }
        public string Titular { get; set; }
        public long DNI { get; set; }
        public string Correo { get; set; }
        public string Tarjeta { get; set; }
        public long NROTarjeta { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public int Precio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boleto> Boletoes { get; set; }
    }
}
