// <auto-generated />
namespace Sistema_final.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class db_cuentas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db_cuentas));
        
        string IMigrationMetadata.Id
        {
            get { return "201909301841113_db_cuentas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
