// <auto-generated />
namespace Sistema_final.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class filas_pb_pa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(filas_pb_pa));
        
        string IMigrationMetadata.Id
        {
            get { return "201910012035068_filas_pb_pa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
