// <auto-generated />
namespace Sistema_final.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class datetime2cliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datetime2cliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201910280312351_datetime2-cliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
